# Generated by Django 5.0.6 on 2024-08-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('interviews', models.ManyToManyField(blank=True, related_name='interviews', to='api.interview')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='api.job'),
        ),
    ]
