# Generated by Django 5.0.6 on 2024-08-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_interview_job_user_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='company',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='interview',
            name='company_description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='job_description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
