# Generated by Django 5.0.6 on 2024-08-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_company_interview_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='resume_text',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
