# Generated by Django 5.0.6 on 2024-08-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_interview_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
