# Generated by Django 5.0.6 on 2024-08-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_interview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(default='incomplete', max_length=20, null=True),
        ),
    ]
