# Generated by Django 5.0.6 on 2024-08-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_interview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=100, null=True)),
                ('user_answer', models.CharField(max_length=10000, null=True)),
                ('feedback', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='api.question'),
        ),
    ]
