openapi: 3.0.0
info:
  title: Django REST API
  description: API documentation for the Django REST API
  version: 1.0.0
paths:
  /:
    get:
      summary: Root Endpoint
      description: Returns a greeting message.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, world!"
components:
  schemas:
    # Define schemas here
